const italianQuotes = [
  "Buongiorno! Inizia la giornata con energia e positività.",
  "Ogni giorno è una nuova opportunità per eccellere.",
  "Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.",
  "Sii la versione migliore di te stesso oggi.",
  "La perseveranza porta al traguardo.",
  "Sorridi, oggi sarà una grande giornata!",
  "Concentrati sui tuoi obiettivi e vai avanti.",
  "La tua energia positiva crea il tuo futuro.",
  "Ogni sfida è un'opportunità di crescita.",
  "Buona fortuna per una giornata produttiva!",
  "Quello che fai oggi può migliorare il domani.",
  "Non aspettare il momento perfetto, prendi il momento e rendilo perfetto.",
  "Credi in te stesso e gli altri crederanno in te.",
  "Il tuo tempo è limitato, non sprecarla vivendo la vita di qualcun altro.",
  "Fare la differenza inizia con una singola azione.",
  "La motivazione è ciò che ti inizia, l'abitudine è ciò che ti continua.",
  "Oggi è il primo giorno del resto della tua vita.",
  "Sei più forte di quanto pensi.",
  "Ogni maestro è stato una volta uno studente.",
  "La tua debolezza di oggi è la forza di domani.",
  "Fai bene le piccole cose: sono quelle che costruiscono i grandi risultati.",
  "La costanza batte il talento quando il talento non e costante.",
  "Ogni passo avanti conta, anche quando sembra piccolo.",
  "Chi semina disciplina raccoglie risultati.",
  "Non serve essere perfetti, serve esserci con impegno.",
  "Le grandi giornate iniziano da decisioni semplici prese bene.",
  "Lavora con cura: i dettagli parlano di te.",
  "Anche oggi hai l'occasione di fare la differenza.",
  "Ogni obiettivo si raggiunge un'azione alla volta.",
  "L'energia che metti oggi torna nei risultati di domani.",
  "La fiducia cresce ogni volta che mantieni una promessa con te stesso.",
  "Continua: spesso il passo decisivo arriva dopo quello piu faticoso.",
  "Non confrontarti con gli altri: migliora te stesso di ieri.",
  "Quando il lavoro e fatto bene, si vede senza bisogno di spiegarlo.",
  "La disciplina di oggi e la serenita di domani.",
  "Una mente lucida e un grande vantaggio operativo.",
  "Il modo migliore per prevedere un buon risultato e prepararlo.",
  "Ogni cliente soddisfatto nasce da attenzione vera.",
  "Resta concentrato: anche una giornata intensa puo essere una grande giornata.",
  "La qualita non e un gesto isolato, e un'abitudine.",
  "La calma e una forza quando gli altri vanno in confusione.",
  "Ogni sfida risolta aumenta il tuo valore.",
  "Chi lavora con metodo va piu lontano di chi corre senza direzione.",
  "Una buona organizzazione rende possibile un grande servizio.",
  "Le difficolta non fermano chi ha chiaro il motivo per cui sta andando avanti.",
  "Scegli il progresso, anche quando e lento.",
  "La pazienza operativa e una forma di intelligenza.",
  "Le giornate migliori si costruiscono con ordine, ritmo e presenza.",
  "Essere affidabili vale quanto essere veloci.",
  "Quando ti prendi cura del lavoro, il lavoro si prende cura dei risultati.",
  "La differenza tra caos e controllo spesso sta in una scelta fatta bene.",
  "Un team forte cresce da persone che fanno bene la loro parte.",
  "La precisione e rispetto per il cliente e per il collega.",
  "La tua presenza conta piu di quanto immagini.",
  "Fermati un secondo, respira, poi riparti meglio.",
  "Ogni giornata porta con se una possibilita concreta di migliorare.",
  "Essere costanti nei giorni normali prepara ai giorni difficili.",
  "Il coraggio non e rumore: spesso e continuita.",
  "La professionalita si vede quando mantieni la qualita anche sotto pressione.",
  "Porta ordine dove c'e confusione e il valore si vedra subito.",
  "Anche oggi puoi trasformare un problema in una soluzione.",
  "Le persone si ricordano di chi rende il lavoro piu semplice.",
  "Un buon inizio aiuta, ma una buona continuita vince.",
  "La fiducia degli altri si conquista con piccoli gesti ripetuti bene.",
  "Dai priorita a cio che conta davvero e il resto si chiarira.",
  "Chi non molla alla prima difficolta costruisce vantaggio vero.",
  "Il lavoro ben fatto e una forma di orgoglio silenzioso.",
  "Le abitudini giuste alleggeriscono anche le giornate complesse.",
  "Non aspettare motivazione perfetta: inizia, e la motivazione ti raggiungera.",
  "Ogni giornata e una nuova occasione per confermare il tuo valore."
];

function quoteIndexForDate(date: Date) {
  const year = date.getFullYear();
  const start = new Date(year, 0, 1);
  const diffMs = date.getTime() - start.getTime();
  const dayOfYear = Math.floor(diffMs / 86_400_000);
  return dayOfYear % italianQuotes.length;
}

export async function getMotivationalQuote(referenceDate: Date = new Date()): Promise<string> {
  return italianQuotes[quoteIndexForDate(referenceDate)];
}
