export interface Database {
  public: {
    Tables: {
      tenants: { Row: { id: string; name: string; created_at: string } };
      memberships: { Row: { user_id: string; tenant_id: string; agency_id: string | null; role: "admin" | "operator" | "driver" | "agency" | "supervisor"; full_name: string; suspended: boolean | null; created_at: string } };
      hotels: { Row: { id: string; tenant_id: string; name: string; address: string; lat: number; lng: number; zone: string; city: string | null; normalized_name: string | null; source: string | null; source_osm_type: string | null; source_osm_id: number | null; is_active: boolean | null; small_vehicle_only: boolean | null; small_vehicle_max_pax: number | null; updated_at: string | null } };
      services: { Row: { id: string; tenant_id: string; inbound_email_id: string | null; is_draft: boolean; agency_id: string | null; date: string; time: string; service_type: "transfer" | "bus_tour"; direction: "arrival" | "departure"; vessel: string; pax: number; hotel_id: string; customer_name: string; billing_party_name: string | null; outbound_time: string | null; return_time: string | null; created_by_user_id: string | null; phone: string; phone_e164: string | null; notes: string; tour_name: string | null; capacity: number | null; low_seat_threshold: number | null; minimum_passengers: number | null; waitlist_enabled: boolean | null; waitlist_count: number | null; meeting_point: string | null; stops: string[] | null; bus_plate: string | null; booking_service_kind: string | null; service_type_code: string | null; customer_first_name: string | null; customer_last_name: string | null; customer_email: string | null; arrival_date: string | null; arrival_time: string | null; departure_date: string | null; departure_time: string | null; transport_code: string | null; train_arrival_number: string | null; train_arrival_time: string | null; train_departure_number: string | null; train_departure_time: string | null; bus_city_origin: string | null; include_ferry_tickets: boolean | null; source_total_amount_cents: number | null; source_price_per_pax_cents: number | null; source_amount_currency: string | null; ferry_details: Record<string, unknown> | null; excursion_details: Record<string, unknown> | null; email_confirmation_to: string | null; email_confirmation_status: string | null; email_confirmation_error: string | null; email_confirmation_sent_at: string | null; share_token: string | null; share_expires_at: string | null; reminder_status: "pending" | "sent" | "delivered" | "read" | "failed" | null; message_id: string | null; sent_at: string | null; status: "needs_review" | "new" | "assigned" | "partito" | "arrivato" | "completato" | "problema" | "cancelled" } };
      assignments: { Row: { id: string; tenant_id: string; service_id: string; driver_user_id: string | null; vehicle_label: string; created_at: string } };
      bus_lot_configs: { Row: { id: string; tenant_id: string; lot_key: string; service_date: string; direction: "arrival" | "departure"; billing_party_name: string | null; bus_city_origin: string | null; transport_code: string | null; title: string | null; meeting_point: string | null; capacity: number; low_seat_threshold: number; minimum_passengers: number | null; waitlist_enabled: boolean; waitlist_count: number; notes: string | null; created_at: string; updated_at: string } };
      status_events: { Row: { id: string; tenant_id: string; service_id: string; status: string; at: string; by_user_id: string } };
      whatsapp_events: { Row: { id: string; tenant_id: string; service_id: string | null; to_phone: string; kind: string | null; template: string | null; status: "queued" | "sent" | "delivered" | "read" | "failed"; provider_message_id: string | null; happened_at: string; payload_json: Record<string, unknown>; created_at: string } };
      tenant_whatsapp_settings: { Row: { tenant_id: string; default_template: string; template_language: string; enable_2h_reminder: boolean; allow_text_fallback: boolean; updated_at: string } };
      vehicles: { Row: { id: string; tenant_id: string; label: string; plate: string | null; capacity: number | null; active: boolean; created_at: string } };
      tenant_geo_settings: { Row: { tenant_id: string; zones: string[]; ports: string[]; updated_at: string } };
      inbound_emails: { Row: { id: string; tenant_id: string; raw_text: string; from_email: string | null; subject: string | null; body_text: string | null; body_html: string | null; raw_json: Record<string, unknown>; extracted_text: string | null; parsed_json: Record<string, unknown>; created_at: string } };
      inbound_email_attachments: { Row: { id: string; inbound_email_id: string; tenant_id: string; filename: string; mimetype: string; size_bytes: number; stored: boolean; extracted_text: string | null; created_at: string } };
    };
  };
}
